# minimal_mistakes_skin: dark # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# site Setting

local			: "ko-kr"
title			: "ChangHee Blog"
title_separator         : "&#124;" # 타이틀 사이 구분자 <title>Welcome to Jekyll | Minimal Mistakes</title> 해당 형식으로 들어갑니다.
subtitle                : "Version 1.0" # 타이틀 아래에 나올 작은 글씨 
name			: "한창희"
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts		: true # set to true to show excerpts on the homepage
url			: "https://sfthch.github.io" # GitBlog 호스트 주소
baseurl			: # subPath https://sfthch.github.io/blog라고 하고 싶을 시 "/blog" 라고 적는다.
author			: "GitHub User"
email			: "sfthch@daum.net"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: ChangHee Han
  tagline: Data Base Admin
# date_format: "%b %-d, %Y"
  date_format: "%Y.%m.%d"
  sitemap: true 
         # set to true to generate sitemap.xml content
  navigation:
    - title: About
      url: "about"
    - title: Works
      url: "works"
  search: true
        # set to true to enable searchbar
  dark_mode: true 
           # set to true to add dark mode toggle
  portfolio_image: "assets/dbeaver256.png" 
                 # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "ko" 
           # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  post_label: 데이타베이스
  condensed_mobile:
  # - home
    - page
    - post
  # generate social links in footer
  social_links:
    # twitter: sfthch
    # github: sfthch
    # linkedIn: in/sfthch
    # dribbble: sfthch
    # flickr: sfthch
    # instagram: sfthch
    # pinterest: sfthch
    # youtube: sfthch
    # facebook: sfthch
    # soundcloud: sfthch
    # telegram: sfthch
    # gitlab: sfthch
    email: sfthch@daum.net

    # Mastodon instances
    # mastodon:
    # - username: sfthch
    #   instance: example.co.kr
    # - username: sfthch2
    #   instance: example.co.kr

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
# theme: plainwhite

plugins:
  - jekyll-seo-tag
# - jekyll-feed
